name: Render Site
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update
      - run: apt-get install python3-sphinx graphviz 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir build
      - run: cmake --version
      - run: cmake -S . -B build
      - run: cmake --build build -j

