name: Render Site
on: workflow_dispatch
jobs:
  Build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install python3-sphinx graphviz 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir build
      - run: cmake --version
      - run: cmake -S . -B build
      - run: cmake --build build -j
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
            path: build/blog/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
